version: '2.4'
services:
  mlfw:
    build: "./"
    working_dir: /app
    restart: "unless-stopped"
    environment:
      TG_API_KEY:
      URL_PATH:
      URL_HOSTNAME:
    #volumes:
    #  - ./code:/app/code:ro
